<div>
    <?php echo $this->form()->openTag($form); ?>
        <?php if ($isUpdate): ?>
            <!-- Disabled fields will not be sent in $_POST so we have to create hidden fields -->
            <?php echo $this->formHidden($form->get('id')); ?>
        <?php endif; ?>
        <table>
            <tr>
                <td colspan="2"><?php echo $this->formElementErrors($form->get('name')); ?></td>
            </tr>
            <tr>
                <td><strong>Name:</strong></td>
                <td><?php echo $this->formElement($form->get('name')) ?></td>
            </tr>

            <tr align="right">
                <td colspan="2"><?php echo $this->formElement($form->get('submit')) ?></td>
            </tr>
        </table>
    <?php echo $this->form()->closeTag(); ?>
</div>