<div>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
        <?php foreach ($tags as $tag): ?>
        <tr>
            <td><a href="<?php echo $this->url('application\tag\view', ['id' => $tag->getId()]) ?>"><?php echo $this->escapeHtml($tag->getId()); ?></a></td>
            <td><?php echo $this->escapeHtml($tag->getName()); ?></td>
            <td><a class="btn btn-success" href="<?php echo $this->url('application\tag\update', array('id' => $tag->getId())); ?>">Update</a></td>
            <td><a class="btn btn-danger" href="<?php echo $this->url('application\tag\delete', array('id' => $tag->getId())); ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="row pagination">
    <div class="col-md-12">
        <?php echo $this->paginationControl(
            $tags,
            'Sliding',
            'application/partial/search-pagination.phtml',
            array('route' => 'application\tag\index/paginator')) ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a class="btn btn-primary" href="<?php echo $this->url('application\tag\create') ?>">Create a new Tag</a>
    </div>
</div>