<div>
    <p><strong>Id:</strong> <?php echo $this->bookmark->getId() ?></p>
    <p><strong>Url:</strong> <?php echo $this->bookmark->getUrl() ?></p>
    <p><strong>Title:</strong> <?php echo $this->bookmark->getTitle() ?></p>
    <p><strong>Description:</strong> <?php echo $this->bookmark->getDescription() ?></p>
    <p><strong>Date:</strong> <?php echo $this->bookmark->getDate() ?></p>
    <p><strong>Votes:</strong> <?php echo $this->bookmark->getVotes() ?></p>
    <p><strong>IdUser:</strong> <?php echo $this->bookmark->getIdUser() ?></p>
</div>